import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SKILLS_ROOT = join(__dirname, '../../skills');

export function generateSkillStub({ name, description, params = [], failureContext = '' }) {
  const skillDir = join(SKILLS_ROOT, `auto-${name}`);
  if (!existsSync(skillDir)) mkdirSync(skillDir, { recursive: true });

  const manifest = {
    name: `auto-${name}`,
    version: '0.1.0',
    description,
    autoGenerated: true,
    generatedAt: new Date().toISOString(),
    failureContext: failureContext.slice(0, 200),
    params: params.map(p => ({ name: p, type: 'string', required: false })),
  };

  const skillJs = `/**
 * Auto-generated skill: ${name}
 * Generated: ${new Date().toISOString()}
 * Context: ${failureContext.slice(0, 100)}
 */
export async function run(params = {}) {
  // TODO: Implement this auto-generated skill
  // Generated from failure analysis — requires manual completion
  return {
    success: false,
    error: 'Skill auto-généré — implémentation requise',
    params,
    autoGenerated: true
  };
}
`;

  const indexJs = `export { run } from './skill.js';\n`;

  const skillMd = `# Skill: auto-${name}\n\n**Auto-généré** — ${new Date().toISOString()}\n\n## Description\n${description}\n\n## Context d'échec\n${failureContext}\n\n## À implémenter\nCe skill a été créé automatiquement suite à une analyse d'échec. Il doit être implémenté manuellement ou via DevAgent.\n`;

  writeFileSync(join(skillDir, 'manifest.json'), JSON.stringify(manifest, null, 2), 'utf8');
  writeFileSync(join(skillDir, 'skill.js'), skillJs, 'utf8');
  writeFileSync(join(skillDir, 'index.js'), indexJs, 'utf8');
  writeFileSync(join(skillDir, 'SKILL.md'), skillMd, 'utf8');

  return { skillName: `auto-${name}`, skillDir, manifest };
}

export async function triggerSkillGeneration(failureAnalysis) {
  if (!failureAnalysis?.shouldGenerateSkill) return null;
  const name = `skill-${Date.now().toString(36)}`;
  const description = `Skill généré pour: ${failureAnalysis.command?.slice(0, 50)}`;
  return generateSkillStub({ name, description, failureContext: failureAnalysis.errors?.join('; ') || '' });
}
