import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SKILLS_ROOT = join(__dirname, '../../skills');

export async function generateSkillStub({ name, description, params = [], failureContext = '' }) {
  const skillDir = join(SKILLS_ROOT, `auto-${name}`);
  if (!existsSync(skillDir)) mkdirSync(skillDir, { recursive: true });

  const manifest = {
    name: `auto-${name}`,
    version: '0.1.0',
    description,
    autoGenerated: true,
    generatedAt: new Date().toISOString(),
    failureContext: failureContext.slice(0, 200),
    params: params.map(p => ({ name: p, type: 'string', required: false })),
  };

  // Call Brain to generate real implementation
  let skillJs;
  try {
    const response = await fetch('http://localhost:8003/raw', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        role: 'worker',
        prompt: `Génère le skill maintenant pour: ${description}\nContexte d'échec: ${failureContext.slice(0, 200)}`,
        system: `Tu génères un skill Node.js ESM pour Ghost OS Ultimate.

Format obligatoire:
\`\`\`javascript
// Skill: ${name} — ${description}
export async function run({ param1, param2 = "default" } = {}) {
  try {
    // implémentation réelle
    return { success: true, result: ... };
  } catch (e) {
    return { success: false, error: e.message };
  }
}
\`\`\`

Règles:
- ESM uniquement (import/export, jamais require)
- Retourner toujours { success: bool, result|error }
- try/catch obligatoire
- Uniquement built-ins Node.js 20 (fs, path, child_process, crypto, fetch natif)
- Zéro dépendance npm externe
- Code production-ready

Réponds UNIQUEMENT avec le code. Sans markdown, sans explication.`
      })
    });
    const data = await response.json();
    let code = data.content || '';
    // Strip markdown fences
    code = code.replace(/```(?:javascript|js)?\n?/g, '').replace(/```/g, '').trim();
    if (code && code.includes('export async function run')) {
      skillJs = code;
    } else {
      throw new Error('LLM did not return valid skill code');
    }
  } catch (e) {
    // Fallback: minimal working stub if Brain unavailable
    skillJs = `// Skill: auto-${name} — ${description}
// Auto-generated (Brain unavailable at generation time — update with real implementation)
export async function run(params = {}) {
  try {
    // TODO: Brain was unavailable — implement manually
    // Context: ${failureContext.slice(0, 80)}
    return { success: false, error: 'Brain unavailable at generation — implement manually', params };
  } catch (e) {
    return { success: false, error: e.message };
  }
}
`;
  }

  const indexJs = `export { run } from './skill.js';\n`;

  const skillMd = `# Skill: auto-${name}\n\n**Auto-généré** — ${new Date().toISOString()}\n\n## Description\n${description}\n\n## Context d'échec\n${failureContext}\n\n## À implémenter\nCe skill a été créé automatiquement suite à une analyse d'échec. Il doit être implémenté manuellement ou via DevAgent.\n`;

  writeFileSync(join(skillDir, 'manifest.json'), JSON.stringify(manifest, null, 2), 'utf8');
  writeFileSync(join(skillDir, 'skill.js'), skillJs, 'utf8');
  writeFileSync(join(skillDir, 'index.js'), indexJs, 'utf8');
  writeFileSync(join(skillDir, 'SKILL.md'), skillMd, 'utf8');

  return { skillName: `auto-${name}`, skillDir, manifest };
}

export async function triggerSkillGeneration(failureAnalysis) {
  if (!failureAnalysis?.shouldGenerateSkill) return null;
  const name = `skill-${Date.now().toString(36)}`;
  const description = `Skill généré pour: ${failureAnalysis.command?.slice(0, 50)}`;
  return await generateSkillStub({ name, description, failureContext: failureAnalysis.errors?.join('; ') || '' });
}
